### ISSUE TITLE
Stops working after a while

### ISSUE THREAD

**Issue by donmega** [losbagos/totalmailboxdeath#1]
This is one of the best scripts ever, thank you. 
One small bug. It doesn't like the gay vegans website, stops working after that:

 ⚘᠂ ⚘ The current url is: https://www.thegayvegans.com/general/
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Wu\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Temp\totalmailboxdeath-main\main.py", line 52, in tmdGoob
    tmdWeb()
  File "C:\Temp\totalmailboxdeath-main\main.py", line 119, in tmdWeb
    tmdWebsite(i)
  File "C:\Temp\totalmailboxdeath-main\main.py", line 107, in tmdWebsite
    driver.get(website)
  File "C:\Users\Wu\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\Wu\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Wu\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=125.0.6422.61)
Stacktrace:
        GetHandleVerifier [0x00007FF6E89022C2+60002]
        (No symbol) [0x00007FF6E887CA59]
        (No symbol) [0x00007FF6E8737D09]
        (No symbol) [0x00007FF6E871FCEE]
        (No symbol) [0x00007FF6E871E205]
        (No symbol) [0x00007FF6E871E9FC]
        (No symbol) [0x00007FF6E873ACB1]
        (No symbol) [0x00007FF6E87CC66E]
        (No symbol) [0x00007FF6E87AC28A]
        (No symbol) [0x00007FF6E87CBCC7]
        (No symbol) [0x00007FF6E87AC033]
        (No symbol) [0x00007FF6E8779657]
        (No symbol) [0x00007FF6E877A251]
        GetHandleVerifier [0x00007FF6E8C13E2D+3278285]
        GetHandleVerifier [0x00007FF6E8C60190+3590448]
        GetHandleVerifier [0x00007FF6E8C561D0+3549552]
        GetHandleVerifier [0x00007FF6E89B1DE6+779654]
        (No symbol) [0x00007FF6E8887ACF]
        (No symbol) [0x00007FF6E8882EE4]
        (No symbol) [0x00007FF6E8883072]
        (No symbol) [0x00007FF6E8872C4F]
        BaseThreadInitThunk [0x00007FFA847C7344+20]
        RtlUserThreadStart [0x00007FFA84B026B1+33]

Keep up the great job!

**Comment by losbagos** [comment]
Thank you so much for your kind words, it means alot! Sorry for the late reply!

I'll remove the gay vegan website for now.

I'll add this to the description as well, but you can use this script on most websites with a newsletter that a) don't use a captcha and b) their newsletter element has the names either 'name', 'NAME', or 'contact[name]', although this can be changed in this line of code:
![image](https://github.com/losbagos/totalmailboxdeath/assets/158247609/020724bb-8de6-4898-b1e4-e7b468b447c3)

And here is how you can find that element
![image](https://github.com/losbagos/totalmailboxdeath/assets/158247609/b37e4ba9-8a21-4b69-af76-4d009363b3c9)

The reason the script only searches these 3 names is because I find these are the most common, with contact[email] being the most common as it seems to be the name of most newsletters plugins! If I add more than 3 I find it really slows down the already slow script. 

Feel free to add any websites you find into the list.txt, I don't screen the websites as well as I should so you may find that don't work well as others! 

Again thank you so much for the kind words and feel free to ask any questions!
